// Shared flat ESLint config (ESLint 9+). Consumers spread this into their own
// eslint.config.js and append framework-specific configs (next/core-web-vitals,
// react-hooks, etc).
import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import importPlugin from 'eslint-plugin-import';
import reactPlugin from 'eslint-plugin-react';
import reactHooksPlugin from 'eslint-plugin-react-hooks';
import tseslint from 'typescript-eslint';

/** @type {import('eslint').Linter.Config[]} */
export const baseConfig = [
  js.configs.recommended,
  ...tseslint.configs.recommended,
  importPlugin.flatConfigs.recommended,
  prettier,
  {
    rules: {
      // GLOBAL RULE: no `any`, no non-null assertions — enforced repo-wide.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-non-null-assertion': 'error',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      // Resolver-dependent import rules: TS's own checker verifies these far
      // more reliably (esModuleInterop/CJS-ESM interop trips up eslint-
      // plugin-import's resolver with frequent false positives).
      'import/no-unresolved': 'off',
      'import/default': 'off',
      'import/named': 'off',
      'import/namespace': 'off',
      'import/order': [
        'warn',
        {
          groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
          'newlines-between': 'always',
          alphabetize: { order: 'asc', caseInsensitive: true },
        },
      ],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },
  {
    ignores: [
      '**/dist/**',
      '**/.next/**',
      '**/.turbo/**',
      '**/.expo/**',
      '**/node_modules/**',
      '**/coverage/**',
      '**/drizzle/**',
      // Auto-generated by `next dev`/`next build` — never hand-edited, and
      // its required triple-slash reference trips @typescript-eslint's rule
      // against them.
      '**/next-env.d.ts',
    ],
  },
];

// Spread this (in addition to baseConfig) for React/React Native packages —
// apps/web, apps/mobile — scoped to their own file globs by the consumer.
/** @type {import('eslint').Linter.Config[]} */
export const reactConfig = [
  {
    plugins: { react: reactPlugin, 'react-hooks': reactHooksPlugin },
    languageOptions: {
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    rules: {
      ...reactPlugin.configs.flat.recommended.rules,
      // Referenced directly rather than via reactHooksPlugin.configs.* — v5's
      // flat-config preset export shape has churned across minor versions;
      // the plugin only ever defines these two rules, so this is stable.
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      'react/react-in-jsx-scope': 'off', // not needed with the modern JSX transform
      'react/prop-types': 'off', // TypeScript covers this
    },
    settings: { react: { version: 'detect' } },
  },
];

export default baseConfig;
